spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_HOST_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    mongodb:
      uri: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_HOST}:${MONGO_HOST_PORT}/${MYSQL_DATABASE}?authSource=admin
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_HOST_PORT}

logging:
  level:
    root: INFO

api:
  youtube:
    key: ${YOUTUBE_API_KEY}
  kis:
    appkey: ${KIS_APP_KEY}
    appsecret: ${KIS_APP_SECRET}
    base-url: https://openapi.koreainvestment.com:9443
